//
// This file was auto-generated from ScriptGraphAsset assets in Unity Project Mesh201.
//

// <auto-generated />

namespace Microsoft.Mesh.CloudScripting
{
    using System;
    using System.Linq;
    using System.Numerics;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class InformationButtonPersistVisualScript : VisualScriptNode
    {
        protected InformationButtonPersistVisualScript(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        public event EventHandler<PropertyChangedBaseEventArgs> StartingScaleChanged
        {
            add => AddPropertyChangedEventHandler(nameof(StartingScale), value);
            remove => RemovePropertyChangedEventHandler(nameof(StartingScale), value);
        }

        public event EventHandler<PropertyChangedBaseEventArgs> PressedScaleChanged
        {
            add => AddPropertyChangedEventHandler(nameof(PressedScale), value);
            remove => RemovePropertyChangedEventHandler(nameof(PressedScale), value);
        }

        public event EventHandler<PropertyChangedBaseEventArgs> AnimationDurationChanged
        {
            add => AddPropertyChangedEventHandler(nameof(AnimationDuration), value);
            remove => RemovePropertyChangedEventHandler(nameof(AnimationDuration), value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float StartingScale
        {
            get => (float)this[nameof(StartingScale)];
            set => this[nameof(StartingScale)].SetValue(value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float PressedScale
        {
            get => (float)this[nameof(PressedScale)];
            set => this[nameof(PressedScale)].SetValue(value);
        }

        [Replication(ReplicationKind.Full)]
        [Serialized(true)]
        public float AnimationDuration
        {
            get => (float)this[nameof(AnimationDuration)];
            set => this[nameof(AnimationDuration)].SetValue(value);
        }

        internal static InformationButtonPersistVisualScript GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new InformationButtonPersistVisualScript(handle, transfer: t));

            return result as InformationButtonPersistVisualScript;
        }
    }
}